apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: minisrv                  # Name of the Kubernetes resource
spec:
  replicas: 2                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: minisrv               # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: minisrv 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: minisrv
        image: host:6000/minisrv
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081  # Should match the port number that the Go application listens on
      